spring.application.name=auth-user-api
server.port=8080

spring.data.mongodb.authentication-database=XXXX
spring.data.mongodb.auto-index-creation=XXXX
spring.data.mongodb.host=XXXX
spring.data.mongodb.port=XXXX
spring.data.mongodb.username=XXXX
spring.data.mongodb.password=XXX


