spring.application.name=auth-user-api
server.port=8080

spring.data.mongodb.host=XXXX
spring.data.mongodb.port=XXXX
spring.data.mongodb.database=XXXX
spring.data.mongodb.username=XXXX
spring.data.mongodb.password=XXXX
spring.data.mongodb.authentication-database=admin

jwt.secret=super-secret-phrase-that-no-one-should-know-32-chars
jwt.expiration=3600000